// Mock data para Inventario - Útil para pruebas en el frontend
export const mockInventarioData = [
  // CARNES
  {
    id: 1,
    nombre: "Pollo pechuga",
    tipo: "Carnes",
    unidades: "kg",
    n_unidades: 25,
    proveedor: "Carnes Rosario",
    precio_unidad: 4.50,
    fecha_registro: "2025-01-10 09:30:00",
  },
  {
    id: 2,
    nombre: "Res molida",
    tipo: "Carnes",
    unidades: "kg",
    n_unidades: 15,
    proveedor: "Distribuidora La Canasta",
    precio_unidad: 6.80,
    fecha_registro: "2025-01-11 10:15:00",
  },
  {
    id: 3,
    nombre: "Costillas de cerdo",
    tipo: "Carnes",
    unidades: "kg",
    n_unidades: 12,
    proveedor: "Carnicería Central",
    precio_unidad: 5.20,
    fecha_registro: "2025-01-12 08:45:00",
  },
  {
    id: 4,
    nombre: "Jamón serrano",
    tipo: "Carnes",
    unidades: "gramos",
    n_unidades: 5000,
    proveedor: "Importadora Ibérica",
    precio_unidad: 0.025,
    fecha_registro: "2025-01-10 14:20:00",
  },

  // PESCADOS
  {
    id: 5,
    nombre: "Salmón fresco",
    tipo: "Pescados",
    unidades: "kg",
    n_unidades: 8,
    proveedor: "Pescadería Mar del Sur",
    precio_unidad: 12.50,
    fecha_registro: "2025-01-12 07:00:00",
  },
  {
    id: 6,
    nombre: "Bacalao desalado",
    tipo: "Pescados",
    unidades: "kg",
    n_unidades: 10,
    proveedor: "Distribuidora Costa Azul",
    precio_unidad: 8.90,
    fecha_registro: "2025-01-11 08:30:00",
  },
  {
    id: 7,
    nombre: "Camarones",
    tipo: "Pescados",
    unidades: "kg",
    n_unidades: 6,
    proveedor: "Mariscos Premium",
    precio_unidad: 15.00,
    fecha_registro: "2025-01-12 06:45:00",
  },
  {
    id: 8,
    nombre: "Mejillones",
    tipo: "Pescados",
    unidades: "kg",
    n_unidades: 20,
    proveedor: "Pescadería Costera",
    precio_unidad: 4.25,
    fecha_registro: "2025-01-10 09:00:00",
  },

  // VERDURAS
  {
    id: 9,
    nombre: "Tomate rojo",
    tipo: "Verduras",
    unidades: "kg",
    n_unidades: 40,
    proveedor: "Huerta Orgánica Del Valle",
    precio_unidad: 1.50,
    fecha_registro: "2025-01-12 05:30:00",
  },
  {
    id: 10,
    nombre: "Cebolla blanca",
    tipo: "Verduras",
    unidades: "kg",
    n_unidades: 35,
    proveedor: "Distribuidor Agrícola",
    precio_unidad: 0.80,
    fecha_registro: "2025-01-12 06:00:00",
  },
  {
    id: 11,
    nombre: "Ajo",
    tipo: "Verduras",
    unidades: "kg",
    n_unidades: 5,
    proveedor: "Productor Local",
    precio_unidad: 3.20,
    fecha_registro: "2025-01-11 07:15:00",
  },
  {
    id: 12,
    nombre: "Pimiento rojo",
    tipo: "Verduras",
    unidades: "kg",
    n_unidades: 20,
    proveedor: "Verduras Frescas SA",
    precio_unidad: 2.10,
    fecha_registro: "2025-01-12 05:45:00",
  },
  {
    id: 13,
    nombre: "Lechuga romana",
    tipo: "Verduras",
    unidades: "unidad",
    n_unidades: 50,
    proveedor: "Huerta Orgánica Del Valle",
    precio_unidad: 0.85,
    fecha_registro: "2025-01-12 06:30:00",
  },

  // ESPECIAS
  {
    id: 14,
    nombre: "Azúcar",
    tipo: "Especias",
    unidades: "kg",
    n_unidades: 100,
    proveedor: "Distribuidora Dulce",
    precio_unidad: 1.20,
    fecha_registro: "2025-01-10 09:00:00",
  },
  {
    id: 15,
    nombre: "Pimienta negra molida",
    tipo: "Especias",
    unidades: "gramos",
    n_unidades: 500,
    proveedor: "Importadora de Especias",
    precio_unidad: 0.08,
    fecha_registro: "2025-01-11 10:45:00",
  },
  {
    id: 16,
    nombre: "Canela en rama",
    tipo: "Especias",
    unidades: "gramos",
    n_unidades: 300,
    proveedor: "Tienda de Especias Exóticas",
    precio_unidad: 0.12,
    fecha_registro: "2025-01-10 11:30:00",
  },
  {
    id: 17,
    nombre: "Comino",
    tipo: "Especias",
    unidades: "gramos",
    n_unidades: 400,
    proveedor: "Distribuidor de Especias",
    precio_unidad: 0.06,
    fecha_registro: "2025-01-11 12:00:00",
  },
  {
    id: 18,
    nombre: "Sal fina",
    tipo: "Especias",
    unidades: "kg",
    n_unidades: 50,
    proveedor: "Salinera Nacional",
    precio_unidad: 0.40,
    fecha_registro: "2025-01-10 08:00:00",
  },

  // LÁCTEOS
  {
    id: 19,
    nombre: "Leche fresca",
    tipo: "Lacteos",
    unidades: "litros",
    n_unidades: 200,
    proveedor: "Lácteos del Sur",
    precio_unidad: 0.60,
    fecha_registro: "2025-01-12 11:00:00",
  },
  {
    id: 20,
    nombre: "Queso cheddar",
    tipo: "Lacteos",
    unidades: "kg",
    n_unidades: 15,
    proveedor: "Quesería Artesanal",
    precio_unidad: 8.50,
    fecha_registro: "2025-01-11 09:30:00",
  },
  {
    id: 21,
    nombre: "Mantequilla",
    tipo: "Lacteos",
    unidades: "gramos",
    n_unidades: 5000,
    proveedor: "Lácteos del Norte",
    precio_unidad: 0.005,
    fecha_registro: "2025-01-12 10:00:00",
  },
  {
    id: 22,
    nombre: "Yogur natural",
    tipo: "Lacteos",
    unidades: "litros",
    n_unidades: 80,
    proveedor: "Lácteos Premium",
    precio_unidad: 1.25,
    fecha_registro: "2025-01-12 10:30:00",
  },
  {
    id: 23,
    nombre: "Crema de leche",
    tipo: "Lacteos",
    unidades: "litros",
    n_unidades: 30,
    proveedor: "Lácteos Selectos",
    precio_unidad: 2.80,
    fecha_registro: "2025-01-11 11:15:00",
  },

  // CEREALES
  {
    id: 24,
    nombre: "Harina de trigo",
    tipo: "Cereales",
    unidades: "kg",
    n_unidades: 50,
    proveedor: "Molinos SA",
    precio_unidad: 0.80,
    fecha_registro: "2025-01-10 09:30:00",
  },
  {
    id: 25,
    nombre: "Arroz blanco",
    tipo: "Cereales",
    unidades: "kg",
    n_unidades: 80,
    proveedor: "Distribuidora Cereal",
    precio_unidad: 0.95,
    fecha_registro: "2025-01-11 08:00:00",
  },
  {
    id: 26,
    nombre: "Avena",
    tipo: "Cereales",
    unidades: "kg",
    n_unidades: 30,
    proveedor: "Cereales Puros",
    precio_unidad: 1.40,
    fecha_registro: "2025-01-12 07:30:00",
  },
  {
    id: 27,
    nombre: "Huevos",
    tipo: "Cereales",
    unidades: "unidad",
    n_unidades: 300,
    proveedor: "Granja Los Pinos",
    precio_unidad: 0.10,
    fecha_registro: "2025-01-12 08:45:00",
  },
  {
    id: 28,
    nombre: "Maíz molido",
    tipo: "Cereales",
    unidades: "kg",
    n_unidades: 40,
    proveedor: "Molino Del Maíz",
    precio_unidad: 0.70,
    fecha_registro: "2025-01-10 10:00:00",
  },

  // ACEITES
  {
    id: 29,
    nombre: "Aceite de oliva extra virgen",
    tipo: "Aceites",
    unidades: "litros",
    n_unidades: 25,
    proveedor: "Aceiteras Mediterráneas",
    precio_unidad: 6.50,
    fecha_registro: "2025-01-11 13:00:00",
  },
  {
    id: 30,
    nombre: "Aceite de girasol",
    tipo: "Aceites",
    unidades: "litros",
    n_unidades: 60,
    proveedor: "Aceitería Nacional",
    precio_unidad: 1.80,
    fecha_registro: "2025-01-12 12:30:00",
  },
  {
    id: 31,
    nombre: "Aceite de coco",
    tipo: "Aceites",
    unidades: "litros",
    n_unidades: 15,
    proveedor: "Productos Tropicales",
    precio_unidad: 4.20,
    fecha_registro: "2025-01-10 14:45:00",
  },

  // BEBIDAS
  {
    id: 32,
    nombre: "Agua mineral",
    tipo: "Bebidas",
    unidades: "litros",
    n_unidades: 500,
    proveedor: "Embotelladora Regional",
    precio_unidad: 0.25,
    fecha_registro: "2025-01-12 06:00:00",
  },
  {
    id: 33,
    nombre: "Jugo de naranja",
    tipo: "Bebidas",
    unidades: "litros",
    n_unidades: 100,
    proveedor: "Exprimidos Frescos",
    precio_unidad: 1.50,
    fecha_registro: "2025-01-12 07:00:00",
  },
  {
    id: 34,
    nombre: "Vino tinto",
    tipo: "Bebidas",
    unidades: "litros",
    n_unidades: 40,
    proveedor: "Bodega Premium",
    precio_unidad: 5.00,
    fecha_registro: "2025-01-11 15:30:00",
  },
  {
    id: 35,
    nombre: "Café molido",
    tipo: "Bebidas",
    unidades: "kg",
    n_unidades: 20,
    proveedor: "Importadora de Café",
    precio_unidad: 7.50,
    fecha_registro: "2025-01-11 14:00:00",
  },
  {
    id: 36,
    nombre: "Té negro",
    tipo: "Bebidas",
    unidades: "gramos",
    n_unidades: 1000,
    proveedor: "Distribuidora de Té",
    precio_unidad: 0.015,
    fecha_registro: "2025-01-10 16:00:00",
  },
];

// Exportar también un tipo TypeScript si es necesario
export interface Inventario {
  id: number;
  nombre: string;
  tipo: "Carnes" | "Pescados" | "Verduras" | "Especias" | "Lacteos" | "Cereales" | "Aceites" | "Bebidas";
  unidades: "kg" | "litros" | "unidad" | "metros" | "gramos";
  n_unidades: number;
  proveedor: string;
  precio_unidad: number;
  fecha_registro: string;
}